wx:
  miniapp:
    configs:
        #haseIT
      - appName: haseIT
        appid: wx9812117be87d24d2
        secret: d86b70d7565f479efabc98b12434f679
        token: hase@1234
        aesKey: Ir3H4X9yrRbOZjpudorc2yGYsAaseQauuVEe5UtkGP9
        msgDataFormat: JSON
        #hacn
      - appName: hacn
        appid: wxf60257610325b729
        secret: 982860fa2a00708062119fd49983e9be
        token:
        aesKey:
        msgDataFormat: JSON
---
app:
  database: huatuo-test
spring:
  profiles: test
  mail:
    username: huatuo_hase_admin@163.com
    host: smtp.163.com
    password: hase0804
    port: 25
    mail:
      smtp:
        auth: true
      starttls:
        enable: true
        required: true
      subject:
        "[CoV Emergency Message] New Reported Case of Coronavirus"
  sms:
    host: 47.106.180.164:8080
    path: /sms/sendSmsByTemplet
    key: abd84853c6299f97
    template:
      register-verify: SMS_182840777
      alert-health-report: SMS_183200260
  datasource:
    url: jdbc:mysql://134.175.111.164:3306/${app.database}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: huatuo-test
    password: hase@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 9090
  tomcat:
    max-threads: 200
    max-connections: 200
    connection-timeout: 3000

---
app:
  database: huatuo
spring:
  profiles: prod
  mail:
    username: huatuo_hase_admin@163.com
    host: smtp.163.com
    password: hase0804
    port: 25
    mail:
      smtp:
        auth: true
      starttls:
        enable: true
        required: true
      subject:
        "[CoV Emergency Message] New Reported Case of Coronavirus"
  sms:
    host: 47.106.180.164:8080
    path: /sms/sendSmsByTemplet
    key: abd84853c6299f97
    template:
      register-verify: SMS_182840777
      alert-health-report: SMS_183200260
  datasource:
    url: jdbc:mysql://134.175.111.164:3306/${app.database}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: huatuo
    password: hase@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
  tomcat:
    max-threads: 200
    max-connections: 200
    connection-timeout: 3000
